### ISSUE TITLE
Create sanitized, GDPR-compliant database dumps

### ISSUE THREAD

**Issue by balintbrews** [BluesparkLabs/spark#11]
(Extracted from #8.)

- Refactor the dump task to allow both a normal dump and a sanitized dump.
- Augment normal `drush sql-dump` commands with [machbarmacher/gdpr-dump](https://github.com/machbarmacher/gdpr-dump) to perform sanitization on the fly.
- Upload sanitized GDPR-compliant database dumps to s3.

We'll need the ability to specify the gdpr-replacements parameter that denote which db tables and columns to sanitize to be stored in `.spark.yml`, but then converted to the required JSON format in the Spark command task so it can be passed to the `gdpr-dump` command.
```
gdpr-replacements: 
  - tableName
      columnName1:  
        formatter: formatterType
        ... 
      columnName1:  
        formatter: formatterType
        ... 
```
